### ISSUE TITLE
Module build failed: ValidationError: CSS Loader Invalid Option

### ISSUE THREAD

**Issue by badsaarow** [nik-zp/Vue-Mqtt-Example#4]
git clone, then `npm run dev`, but compile error message show as below.

```
 ERROR  Failed to compile with 1 errors                                                                                                                                       9:29:09 PM

 error  in ./src/App.vue

Module build failed: ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/Users/Workspace/vue/Vue-Mqtt-Example/node_modules/css-loader/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/Users/Workspace/vue/Vue-Mqtt-Example/node_modules/css-loader/dist/index.js:44:28)

 @ ./~/vue-style-loader!./~/css-loader/dist/cjs.js?{"minimize":false,"sourceMap":false}!./~/vue-loader/lib/style-compiler?{"vue":true,"id":"data-v-0b6e3b1d","scoped":false,"hasInlineCo
nfig":false}!./~/vue-loader/lib/selector.js?type=styles&index=0!./src/App.vue 4:14-319 13:3-17:5 14:22-327
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js
```

**Comment by denisvitez** [comment]
I am having the same exact issue. I guess it is related with the recent update of dependencies, so I will try to checkout an older commit.

**Comment by denisvitez** [comment]
> I am having the same exact issue. I guess it is related with the recent update of dependencies, so I will try to checkout an older commit.

I tried to checkout and run a commit 37dd601f8a1aedfd61529fb2390dc2c971e1c7a4 and it is indeed working. Unfortunately I'm recet to the world of Vue development so I have no idea how to fix the problem with new dependencies.
